Models/Situation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using PinewoodGrow.Models.Audit;

namespace PinewoodGrow.Models
{
	public class Situation : Auditable
	{
        public Situation()
        {
            MemberSituations = new HashSet<MemberSituation>();
        }
        public int ID { get; set; }

        [Display(Name = "Situation")]
        [Required(ErrorMessage = "You cannot leave the Situation blank.")]
        [StringLength(50, ErrorMessage = "Name cannot be more than 50 characters long.")]
        public string Name { get; set; }

        public ICollection<MemberSituation> MemberSituations { get; set; }
    }
}

Controllers/SituationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PinewoodGrow.Data;
using PinewoodGrow.Models;
using Microsoft.AspNetCore.Authorization;

namespace PinewoodGrow.Controllers
{
    [Authorize]
    public class SituationsController : Controller
    {
        private readonly GROWContext _context;

        public SituationsController(GROWContext context)
        {
            _context = context;
        }

        // GET: Situations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Situations.ToListAsync());
        }

        // GET: Situations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var situation = await _context.Situations
                .FirstOrDefaultAsync(m => m.ID == id);
            if (situation == null)
            {
                return NotFound();
            }

            return View(situation);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        // GET: Situations/Create
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        // POST: Situations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Situation situation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(situation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(situation);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        // GET: Situations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var situation = await _context.Situations.FindAsync(id);
            if (situation == null)
            {
                return NotFound();
            }
            return View(situation);
        }

        [Authorize(Roles = "Admin, SuperAdmin")]
        // POST: Situations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Situation situation)
        {
            if (id != situation.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(situation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SituationExists(situation.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(situation);
        }

        // GET: Situations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var situation = await _context.Situations
                .FirstOrDefaultAsync(m => m.ID == id);
            if (situation == null)
            {
                return NotFound();
            }

            return View(situation);
        }

        // POST: Situations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var situation = await _context.Situations.FindAsync(id);
            try
            {
                _context.Situations.Remove(situation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("FOREIGN KEY constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to Delete Living Situation. You cannot delete a Living Situation that Members have.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(situation);
        }

        private bool SituationExists(int id)
        {
            return _context.Situations.Any(e => e.ID == id);
        }
    }
}

Views/Situations/Create.cshtml
@model PinewoodGrow.Models.Situation

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Income Source</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Income Source</label><label class="text-danger" style="margin:5px;padding:0;">*</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>*@
            <div class="row" style="margin: 0 auto; align-content: center; justify-content:center;">
                <div class="form-group" style="padding-right: 20px">
                    <a asp-action="Index" class="btn btn-primary">Back</a>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-info" />
                </div>
            </div>
        </form>
    </div>
</div>
@*
<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Situations/Delete.cshtml
@model PinewoodGrow.Models.Situation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Situation</h4>
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <dl class="row">
        <dt class = "col-sm-2">
            Income Source
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Situations/Details.cshtml
@model PinewoodGrow.Models.Situation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <div>
        <div class="table-responsive-lg">
            <table class="table table-striped">
                <thead>
                    <tr>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="col">@Html.DisplayNameFor(model => model.Name)</th>
                        <td>@Html.DisplayFor(model => model.Name)</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>

<div class="row" style="margin: 0 auto; padding: 10px; justify-content:center;">
    <div class="form-group" style="padding-right: 20px">
        <a asp-action="Index" class="btn btn-primary">Back</a>
    </div>
    <div class="form-group">
        <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-info">Edit</a>
    </div>
</div>
@*
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
*@

Views/Situations/Edit.cshtml
@model PinewoodGrow.Models.Situation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Income Source</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Income Source</label><label class="text-danger" style="margin:5px;padding:0;">*</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>*@

            <div class="row" style="margin: 0 auto; padding: 10px; align-content: center; justify-content:center;">
                <div class="form-group" style="padding-right: 20px">
                    <a asp-action="Index" class="btn btn-primary">Back</a>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-info" />
                </div>
            </div>
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index">Back to List</a>
</div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Situations/Index.cshtml
@model IEnumerable<PinewoodGrow.Models.Situation>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="/css/Index.css?version=2" />

<br />
<div class="title-index">
    <h1 style="text-align: center">Income Sources</h1>
</div>
<div class="actionsContainer-index" style="top: 45px;">
	<div class="btn-index">
		@if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
		{
			<a style="width: 120px;" asp-controller="Situations" asp-action="Create">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
					<path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
					<path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z" />
				</svg>
				<span>Create</span>
			</a>
		}
		</div>

</div>
<style>
    table {
        margin: 0 auto;
    }
</style>

<br />
<br />
<br />
<br />
<table class="custom-table">
    <thead>
        <tr>
            <th>
                Income Sources
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                     <div class="actionsContainer-table">
                                <div class="btn-index small purple">
                                    <a title="Edit" asp-action="Edit" asp-route-id="@item.ID">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                        </svg>

                                    </a>
                                </div>
                                <div class="btn-index small red">
                                    <a title="Delete" asp-action="Delete" asp-route-id="@item.ID">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                </td>
            </tr>
        }
    </tbody>
</table>