Models/Volunteer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PinewoodGrow.Models
{
    public class Volunteer
    {
        public Volunteer()
        {
            Members = new HashSet<Member>();
        }
        public int ID { get; set; }

        public string Name => FirstName + " " + LastName;

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "You cannot leave the First Name blank.")]
        [StringLength(50, ErrorMessage = "First Name cannot be more than 50 characters long.")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "You cannot leave the Last Name blank.")]
        [StringLength(50, ErrorMessage = "Last Name cannot be more than 50 characters long.")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "You cannot leave the Email blank.")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public ICollection<Member> Members { get; set; }
    }
}

Controllers/VolunteersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using PinewoodGrow.Data;
using PinewoodGrow.Models;
using Microsoft.AspNetCore.Authorization;
using PinewoodGrow.Utilities;

namespace PinewoodGrow.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class VolunteersController : Controller
    {
        private readonly GROWContext _context;
        private readonly ApplicationDbContext _identityContext;
        private readonly IMyEmailSender _emailSender;

        public VolunteersController(GROWContext context, ApplicationDbContext identityContext, IMyEmailSender emailSender)
        {
            _context = context;
            _identityContext = identityContext;
            _emailSender = emailSender;
        }

        // GET: Volunteers
        public async Task<IActionResult> Index(string SearchString, bool IsActive, int? page, int? pageSizeID, string actionButton,
            string sortDirection = "asc", string sortField = "Name")
        {
            string[] sortOptions = new[] { "Name"};

            var volunteers = from v in _context.Volunteers
            select v;


            if (IsActive == true)
            {
                volunteers = volunteers.Where(v => v.Active == false);
            }
            else if (IsActive == false)
            {
                volunteers = volunteers.Where(v => v.Active == true);
            }


            if (!String.IsNullOrEmpty(SearchString))
            {
                volunteers = volunteers.Where(v => v.LastName.ToUpper().Contains(SearchString.ToUpper())
                                              || v.FirstName.ToUpper().Contains(SearchString.ToUpper()));
                ViewData["Filtering"] = " show";
            }

            if (!String.IsNullOrEmpty(actionButton))
            {
                page = 1;
                if (sortOptions.Contains(actionButton))
                {
                    if (actionButton == sortField)
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton;
                }
            }

            if (sortField == "Name")
            {
                if (sortDirection == "asc")
                {
                    volunteers = volunteers
                        .OrderBy(v => v.LastName)
                        .ThenBy(v => v.FirstName);
                }
                else
                {
                    volunteers = volunteers
                        .OrderByDescending(v => v.LastName)
                        .ThenByDescending(v => v.FirstName);
                }
            }

            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;

            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID);
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<Volunteer>.CreateAsync(volunteers.AsNoTracking(), page ?? 1, pageSize);

            //return View(await members.ToListAsync());
            return View(pagedData);
        }

        // GET: Volunteer/Create
        public IActionResult Create()
        {
            Volunteer volunteer = new Volunteer();
            return View(volunteer);
        }

        // POST: Volunteer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Email,Phone")] Volunteer volunteer)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(volunteer);
                    await _context.SaveChangesAsync();
                    TempData["AlertMessage"] = "Volunteer Added Successfully....!";
                    //Send Email to new Volunteer - commented out till email configured
                    //await InviteUserToRegister(volunteer, null);

                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("UNIQUE constraint failed"))
                {
                    ModelState.AddModelError("Email", "Unable to save changes. Remember, you cannot have duplicate Email addresses.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }

            return View(volunteer);
        }

        private async Task InviteUserToRegister(Volunteer volunteer, string message)
        {
            message ??= "Hello " + volunteer.FirstName + "<br /><p>Please navigate to:<br />" +
                        "<a href='https://https://pinewoodgrow.azurewebsites.net//' title='https://https://pinewoodgrow.azurewebsites.net//' target='_blank' rel='noopener'>" +
                        "https://summercamp2022.azurewebsites.net</a><br />" +
                        " and Register using " + volunteer.Email + " for email address.</p>";
            //Sending the email commented out until the service is configured.
            await _emailSender.SendOneAsync(volunteer.FullName, volunteer.Email,
                "Account Registration", message);
            TempData["message"] = "Invitation email sent to " + volunteer.FullName + " at " + volunteer.Email;

        }

        // GET: Volunteers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volunteer = await _context.Volunteers.FindAsync(id);
            if (volunteer == null)
            {
                return NotFound();
            }
            return View(volunteer);
        }

        // POST: Volunteers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, bool Active)
        {
            var volunteerToUpdate = await _context.Volunteers
                .FirstOrDefaultAsync(v => v.ID == id);
            if (volunteerToUpdate == null)
            {
                return NotFound();
            }

            //Note the current Email and Active Status
            bool ActiveStatus = volunteerToUpdate.Active;
            string currentEmail = volunteerToUpdate.Email;

            if (await TryUpdateModelAsync<Volunteer>(volunteerToUpdate, "",
                v => v.FirstName, v => v.LastName, v => v.Email, v => v.Phone, v => v.Active))
            {
                try
                {
                    await _context.SaveChangesAsync();

                    //Delete Login if you are making them inactive
                    if (volunteerToUpdate.Active == false && ActiveStatus == true)
                    {
                        //This deletes the user's login from the security system
                        await DeleteIdentityUser(volunteerToUpdate.Email);

                    }
                    //Delete old Login if you Changed the email
                    if (volunteerToUpdate.Email != currentEmail)
                    {
                        //This deletes the user's login from the security system
                        await DeleteIdentityUser(currentEmail);
                    }
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VolunteerExists(volunteerToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException dex)
                {
                    if (dex.GetBaseException().Message.Contains("UNIQUE constraint failed"))
                    {
                        ModelState.AddModelError("Email", "Unable to save changes. Remember, you cannot have duplicate Email addresses.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                    }
                }
            }
            return View(volunteerToUpdate);
        }

        /*public IActionResult Roles()
        {
            var RolesU = _context.RolesWithUsers
                .AsNoTracking()
                .ToList();
            return View(RolesU);
        }*/

        private async Task DeleteIdentityUser(string Email)
        {
            var userToDelete = await _identityContext.Users.Where(u => u.Email == Email).FirstOrDefaultAsync();
            if (userToDelete != null)
            {
                _identityContext.Users.Remove(userToDelete);
                await _identityContext.SaveChangesAsync();
            }
        }

        private bool VolunteerExists(int id)
        {
            return _context.Volunteers.Any(v => v.ID == id);
        }
    }
}

Views/Volunteers/Create.cshtml
@model PinewoodGrow.Models.Volunteer

@{
    ViewData["Title"] = "Create Volunteer";
}

<h2>Create Volunteer</h2>

<hr />

<form asp-action="Create">
    <div class="row">
        <div class="col-md-4">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Active" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label><label class="text-danger" style="margin:5px;padding:0;">*</label>
                <input asp-for="FirstName" class="form-control" autofocus />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label><label class="text-danger" style="margin:5px;padding:0;">*</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label><label class="text-danger" style="margin:5px;padding:0;">*</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="row" style="margin: 0 auto; align-content: center; justify-content:center;">
                <div class="form-group" style="padding-right: 20px">
                    <a asp-action="Index" class="btn btn-primary">Back</a>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-info" />
                </div>
            </div>
        </div>
        
    </div>
    
</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Volunteers/Edit.cshtml
@model PinewoodGrow.Models.Volunteer

@{
    ViewData["Title"] = "Edit Volunteer";
}

<h4>Account Details for @Model.FullName (@Model.Email)</h4>
<hr />
<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
		<div class="col-md-4">
			<input type="hidden" asp-for="ID" />
			<div class="form-group">
				<label asp-for="FirstName" class="control-label"></label><label class="text-danger" style="margin:5px;padding:0;">*</label>
				<input asp-for="FirstName" class="form-control" />
				<span asp-validation-for="FirstName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="LastName" class="control-label"></label><label class="text-danger" style="margin:5px;padding:0;">*</label>
				<input asp-for="LastName" class="form-control" />
				<span asp-validation-for="LastName" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Email" class="control-label"></label><label class="text-danger" style="margin:5px;padding:0;">*</label>
				<input asp-for="Email" class="form-control" />
				<span asp-validation-for="Email" class="text-danger"></span>
				<div>
					Note:  Changing Email will remove the Login and the user will need to register again with the new Email.
				</div>
			</div>
			<div class="form-group">
				<label asp-for="Phone" class="control-label"></label>
				<input asp-for="Phone" class="form-control" />
				<span asp-validation-for="Phone" class="text-danger"></span>
			</div>

			<div class="form-group form-check">
				<label class="form-check-label">
					<input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
				</label>
				@{
					if (Model.Active == true)
					{
						<div><strong>Warning! Making this volunteer inactive will also remove their login. To add them back in you must register their account again with the same email address.</strong></div>
					}
					else
					{
						<div><strong>If you make this user active, you must also Register their login again, using the same email address.  Afterwards you can add them to security roles as required.</strong></div>
					}
				}
			</div>
			<div class="row" style="margin: 0 auto; align-content: center; justify-content:center;">
				<div class="form-group" style="padding-right: 20px">
					<a asp-action="Index" class="btn btn-primary">Back</a>
				</div>
				<div class="form-group">
					<input type="submit" value="Save" class="btn btn-info" />
				</div>
			</div>
		</div>
    </div>
</form>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Volunteers/Index.cshtml
@model IEnumerable<PinewoodGrow.Models.Volunteer>

@{
    ViewData["Title"] = "Index";
}
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-success">
        <strong>Success !</strong> @TempData["AlertMessage"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>

}

<link rel="stylesheet" href="/css/Index.css?version=2" />

<br />
<div class="title-index">
    <h1 style="text-align: center">Volunteers</h1>
</div>
<div class="actionsContainer-index" style="top: 45px;">
    <div class="btn-index">
        <a style="width: 120px;" asp-controller="Volunteers" asp-action="Create">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
            </svg>
            <span>Create</span>
        </a>
    </div>

</div>
<style>
    table {
        margin: 0 auto;
    }
</style>

<br />

@*<p>
    <a asp-action="Create" class="btn btn-sm btn-info right float-right">Create New Volunteer</a>
</p>*@

<div class="text-danger">@TempData["message"]</div>

<form asp-action="Index" method="get">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
    <div class="form-horizontal">
        <br />
        <button class="btn btn-outline-secondary" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
            Filter/Search
        </button>
        <div class="collapse @(ViewData["Filtering"])" id="collapseFilter">
            <div class="card card-body bg-light">
                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label">Search by Name:</label>
                        @Html.TextBox("SearchString", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Filter by Inactive:</label>
                        @Html.CheckBox("IsActive", false, new { @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-4 align-self-end">
                        <input type="submit" name="actionButton" value="Filter" class="btn btn-outline-primary" />
                        <a asp-action="Index" class="btn btn-outline-dark">Clear</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <table class="custom-table">
        <thead>
            <tr>
                <th>
                    <input type="submit" name="actionButton" value="Name" class="btn btn-link no-decoration" />
                    @{
                        if ((string)ViewData["sortField"] == "Name")
                        {
                            if ((string)ViewData["sortDirection"] == "asc")
                            {
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z" />
                                </svg>
                            }
                            else
                            {
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" />
                                </svg>
                            }

                        }
                        else if ((string)ViewData["sortField"] == "")
                        {
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z" />
                            </svg>
                        }
                    }
                </th>
                <th>
                    Email
                    @*<input type="submit" disabled="disabled" value="Email" class="btn btn-link" />*@
                </th>
                <th>
                    Phone Number
                    @*<input type="submit" disabled="disabled" value="Phone Number" class="btn btn-link" />*@
                </th>
                <th>
                    Active
                    @*<input type="submit" disabled="disabled" value="Active" class="btn btn-link" />*@
                </th>
    </table>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <input type="submit" name="actionButton" value="Name" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" disabled="disabled" value="Email" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" disabled="disabled" value="Phone Number" class="btn btn-link" />
                </th>
                <th>
                    <input type="submit" disabled="disabled" value="Active" class="btn btn-link" />
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                    <td>
                        <div class="actionsContainer-table">

                            <div class="btn-index small">
                                <a title="Edit" asp-action="Edit" asp-route-id="@item.ID">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                        <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                                    </svg>
                                </a>
                            </div>


                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>

@section Scripts {
    <script type="text/javascript">
        window.setTimeout(function () {
            $(".alert").fadeTo(2000, 0).slideUp(2000, function () {
                $(this).remove();
            })
        })
    </script>
}