Models/Temp/TempMember.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using PinewoodGrow.Models.Audit;

namespace PinewoodGrow.Models.Temp
{
    public class TempMember : Auditable
    {
        public TempMember()
        {
            MemberSituations = new HashSet<TempMemberSituation>();
            MemberDietaries = new HashSet<TempMemberDietary>();
            MemberIllnesses = new HashSet<TempMemberIllness>();
            MemberDocuments = new HashSet<TempMemberDocument>();
            MemberHouseholds = new HashSet<TempMemberHousehold>();
        }

        public bool isValid => CheckValid();








        public string FullName => FirstName + " " + LastName;

        [Display(Name = "Age (DOB)")]
        public string AgeSummary
        {
            get
            {
                string ageSummary = "Unknown";
                if (DOB.HasValue)
                {
                    ageSummary = Age + " (" + String.Format("{0:yyyy-MM-dd}", DOB) + ")";
                }
                return ageSummary;
            }
        }

        public string Age
        {
            get
            {
                DateTime today = DateTime.Today;
                int? a = today.Year - DOB?.Year
                                    - ((today.Month < DOB?.Month || (today.Month == DOB?.Month && today.Day < DOB?.Day) ? 1 : 0));
                return a?.ToString(); /*Note: You could add .PadLeft(3) but spaces disappear in a web page. */
            }
        }

        public double Income => MemberSituations.Select(a=> a.SituationIncome).ToList().Sum();

		public int ID { get; set; }


		public string FirstName { get; set; }


		public string LastName { get; set; }

		/*[Required(ErrorMessage = "You cannot leave the Age blank.")]
		[Range(1, 115, ErrorMessage = "Age must be greater than 0.")]
		public int Age { get; set; }*/

        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]

		public DateTime? DOB { get; set; }


		public string Telephone { get; set; }

		public string Email { get; set; }

        public string Notes { get; set; }

		public bool Consent { get; set; }

	
		public int? VolunteerID { get; set; }
		public Volunteer Volunteer { get; set; }

	
		public DateTime CompletedOn { get; set; }


		public int? TempHouseholdID { get; set; }
		public TempHousehold TempHousehold { get; set; }
        public int? HouseholdID { get; set; }
        public Household Household { get; set; }


		public int? GenderID { get; set; }
		public Gender Gender { get; set; }

		public ICollection<TempMemberSituation> MemberSituations { get; set; }
        public ICollection<TempMemberDietary> MemberDietaries { get; set; }

		public ICollection<TempMemberIllness> MemberIllnesses { get; set; }
        public ICollection<TempMemberDocument> MemberDocuments { get; set; }

		public ICollection<TempMemberHousehold> MemberHouseholds { get; set; }


        private bool CheckValid()
        {
            if (!ValidateName(FirstName)) return false;
            if (!ValidateName(LastName)) return false;
            if (string.IsNullOrEmpty(Telephone)) return false;
            if (Telephone.Length > 11) return false;
            if (string.IsNullOrEmpty(Email)) return false;
            if(!string.IsNullOrEmpty(Notes)) if (Notes.Length > 2000) return false;
            if (GenderID == null || GenderID == 0) return false;
            if (DOB.GetValueOrDefault() > DateTime.Today) return false;
            var age = (DateTime.Today.Year - DOB.GetValueOrDefault().Year) -
                      ((-DOB.GetValueOrDefault().Month + DOB.GetValueOrDefault().Day) >=
                       (-DateTime.Today.Month + DateTime.Today.Day) ? 1 : 0);

            if (age > 100 || age < 18) return false; 
              


            return Consent;


        }

        private bool ValidateName(string name)
        {
            if (string.IsNullOrEmpty(name)) return false;
            if (name.Length > 50) return false;
            return true;
        }
	}
}

Controllers/TempMembersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PinewoodGrow.Data;
using PinewoodGrow.Models.Temp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore.Storage;
using PinewoodGrow.Models;
using PinewoodGrow.ViewModels;

namespace PinewoodGrow.Controllers
{
    [Authorize]
    public class TempMembersController : Controller
    {
        private readonly GROWContext _context;
        public PartialViewResult MemberSituationList(int id)
        {
            ViewBag.MemberSituations = _context.TempMemberSituations
                .Include(s => s.Situation)
                .Where(s => s.MemberID == id)
                .OrderBy(s => s.Situation.Name)
                .ToList();
            return PartialView("_MemberSituationList");
        }
        public TempMembersController(GROWContext context)
        {
            _context = context;
        }


        public PartialViewResult CreateTempMember(int? ID)
        {

            var tempMember = new TempMember()
            {
                TempHouseholdID = ID,
                CompletedOn = DateTime.Today
            };
            _context.TempMembers.Add(tempMember);
            _context.SaveChanges();





            PopulateAssignedDietaryData(tempMember);
            PopulateAssignedSituationData(tempMember);
            PopulateAssignedIllnessData(tempMember);
            PopulateAssignedDietaryData(tempMember);
            PopulateDropDownLists();

            ViewData["MemberIncomeTypes"] = _context.Situations.Select(a => a);
            ViewData["TempMemberID"] = tempMember.ID;
            ViewData["HouseholdID"] = ID.GetValueOrDefault();

            return PartialView("_CreateTempMember", tempMember);
        }



        public PartialViewResult EditTempMember(int ID)
        {
            //Get the TempMemberSituation to edit
            var tempMember = _context.TempMembers.Include(a=> a.MemberSituations).Include(a=> a.MemberDietaries).Include(a=> a.MemberIllnesses).FirstOrDefault(a => a.ID == ID);
            PopulateAssignedDietaryData(tempMember);
            PopulateAssignedSituationData(tempMember);
            PopulateAssignedIllnessData(tempMember);
            PopulateAssignedDietaryData(tempMember);
            PopulateDropDownLists();

            ViewData["MemberIncomeTypes"] = _context.Situations.Select(a => a);
            ViewData["TempMemberID"] = tempMember.ID;
            ViewData["HouseholdID"] = ID;

            return PartialView("_EditTempMember", tempMember);
        }

        public PartialViewResult DeleteTempMember(int ID)
        {
            //Get the one to delete
            var TempMember = _context.TempMembers.FirstOrDefault(a => a.ID == ID);


            return PartialView("_DeleteTempMember", TempMember);
        }









        // GET: TempMembers
        public async Task<IActionResult> Index()
        {
            var gROWContext = _context.TempMembers.Include(t => t.Gender).Include(t => t.Household)
                .Include(t => t.TempHousehold).Include(t => t.Volunteer);
            return View(await gROWContext.ToListAsync());
        }

        // GET: TempMembers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tempMember = await _context.TempMembers
                .Include(t => t.Gender)
                .Include(t => t.Household)
                .Include(t => t.TempHousehold)
                .Include(t => t.Volunteer)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (tempMember == null)
            {
                return NotFound();
            }

            return View(tempMember);
        }

        // GET: TempMembers/Create
        public IActionResult Create()
        {
            /*var now = DateTime.Now;
         var zeroDate = DateTime.MinValue.AddHours(now.Hour).AddMinutes(now.Minute).AddSeconds(now.Second).AddMilliseconds(now.Millisecond);*/

            var Tempmember = new TempMember()
            {
            };
            _context.TempMembers.Add(Tempmember);
            _context.SaveChanges();


 


            PopulateAssignedDietaryData(Tempmember);
            PopulateAssignedSituationData(Tempmember);
            PopulateAssignedIllnessData(Tempmember);
            PopulateDropDownLists();

            ViewData["MemberIncomeTypes"] = _context.Situations.Select(a => a);
            ViewData["TempMemberID"] = Tempmember.ID;
            return View(Tempmember);
        }

        // POST: TempMembers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,Age,DOB,Telephone,Email,FamilySize,Income" +
            ",Notes,Consent,VolunteerID,CompletedOn,HouseholdID,GenderID")] TempMember member,
                 string[] selectedOptions, string[] selectedSituationOptions, string[] selectedIllnessOptions, List<IFormFile> theFiles, int TempID, int memID
                 )
        //string Lat, string Lng, string AddressName, string postal, string city
        {
            try
            {
                //member.AddressID =  await GetAddressID(Lat, Lng, AddressName, postal, city);
                UpdateMemberDietaries(selectedOptions, member);

                if (ModelState.IsValid)
                {
                    await AddDocumentsAsync(member, theFiles);
                    _context.Add(member);
                    await _context.SaveChangesAsync();

                    var Situations = _context.TempMemberSituations.Where(a => a.MemberID == TempID).Select(a => new MemberSituation
                    { MemberID = member.ID, SituationID = a.SituationID, SituationIncome = a.SituationIncome }).ToList();

                    await _context.AddRangeAsync(Situations);
                    await _context.SaveChangesAsync();

                    /*if (selectedDietaryOptions != null)
                    {
                        foreach (var dietary in selectedDietaryOptions)
                        {
                            var dietaryToAdd = new MemberDietary { MemberID = member.ID, DietaryID = int.Parse(dietary) };
                            member.MemberDietaries.Add(dietaryToAdd);
                        }
                    }*/
           
                    if (selectedIllnessOptions != null)
                    {
                        foreach (var illness in selectedIllnessOptions)
                        {
                            var illnessToAdd = new TempMemberIllness { MemberID = member.ID, IllnessID = int.Parse(illness) };
                            member.MemberIllnesses.Add(illnessToAdd);
                        }
                    }


                    return RedirectToAction(nameof(Index));
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                ModelState.AddModelError("", "Unable to save changes after multiple attempts. Try again, and if the problem persists, see your system administrator.");
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("UNIQUE"))
                {
                    ModelState.AddModelError("", "Unable to save: Duplicate Email Addresses.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes to the database. Try again, and if the problem persists see your system administrator.");
                }
            }
            PopulateAssignedSituationData(member);
            PopulateAssignedDietaryData(member);
            PopulateAssignedIllnessData(member);
            PopulateDropDownLists(member);
            return View(member);
        }


        // POST: TempMembers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int TempID, int id, string[] selectedOptions, string[] selectedDietOptions, string[] selectedSituationOptions
            , string[] selectedIllnessOptions, List<IFormFile> theFiles)
        {
            id = TempID;
            var tempMemberToUpdate = await _context.TempMembers
                //.Include(m => m.Address)
                .Include(m => m.MemberDocuments)
                .Include(m => m.MemberDietaries).ThenInclude(m => m.Dietary)
                .Include(m => m.MemberIllnesses).ThenInclude(m => m.Illness)
                .FirstOrDefaultAsync(m => m.ID == TempID);

            if (tempMemberToUpdate == null)
            {
                return NotFound();
            }

            UpdateMemberDietaries(selectedDietOptions, tempMemberToUpdate);
            UpdateMemberSituation(selectedSituationOptions, tempMemberToUpdate);
            UpdateMemberIllnesses(selectedIllnessOptions, tempMemberToUpdate);

            if (await TryUpdateModelAsync<TempMember>(tempMemberToUpdate, "", m => m.FirstName, m => m.LastName,
                    m => m.DOB, m => m.Telephone,
                    m => m.Email, m => m.Notes, m => m.Consent, m => m.VolunteerID, m => m.CompletedOn,
                    m => m.HouseholdID, m => m.GenderID))
                //m => m.FamilySize, m => m.AddressID, m => m.Address
            {
                try
                {
                    await AddDocumentsAsync(tempMemberToUpdate, theFiles);

Views/TempMembers/Index.cshtml
@model IEnumerable<PinewoodGrow.Models.Temp.TempMember>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telephone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Income)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Consent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Volunteer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CompletedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TempHousehold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Household)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Income)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Consent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Volunteer.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CompletedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempHousehold.FamilyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Household.FamilyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/TempMembers/_CreateTempMember.cshtml
@model PinewoodGrow.Models.Temp.TempMember





<partial name="_MemberSituationModal" />
<partial name="_addDietaryModal" />
<partial name="_addIllnessModal" />
<partial name="_AddDepentandModal" />
<form asp-action="Edit"  asp-controller="TempMembers" id="TempMemberForm" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <input type="button" id="btnSampleData" value="Sample Data" class="btn btn-info" />
    </div>
    <input type="hidden" id="Lat" name="Lat" />
    <input type="hidden" id="Lng" name="Lng" />
    <input type="hidden" id="AddressName" name="AddressName" />

    <input type="hidden" id="TempID" name="TempID" value="@Model.ID" />

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-6">
            <h2>Personal info</h2>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" id="txtFirstName" placeholder="e.g. John"/>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" id="txtLastName" placeholder="e.g. Doe"/>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" class="form-control" id="txtAge"/>
                <span asp-validation-for="DOB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderID" class="control-label"></label>
                <select asp-for="GenderID" class="form-control" id="ddlGender" asp-items="ViewBag.GenderID">
                    <option value="">Select a Gender</option>
                </select>
                <span asp-validation-for="GenderID" class="text-danger"></span>
            </div>
            <h2>Contact Info</h2>
            <div class="form-group">
                <label asp-for="Telephone" class="control-label"></label>
                <input asp-for="Telephone" class="form-control" id="txtPhone" placeholder="e.g. 6367727345"/>
                <span asp-validation-for="Telephone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" id="txtEmail" placeholder="e.g. johndoe@gmail.com"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <textarea asp-for="Notes" class="form-control" placeholder="Please Enter any Additional Information"></textarea>
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Upload Documents:</label>
                <input type="file" class="" name="theFiles" multiple="multiple"/>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Consent"/> To continue, you must agree to the Privacy Policy and Terms of Use.
                </label>
            </div>
        </div>
        <div class="col-md-6">
        <div class="form-group">
            <h2>Dietary Restrictions</h2>
			<div class="col-md-offset-1">
				@if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
				{
					<button class="btn btn-outline-secondary btn-sm" id="nowAddDietary"
							data-toggle="modal" data-target="#addDietaryModal"
							type="button">
						<strong>Add Restriction</strong>
					</button>
				}
				<div class="checkContainer" id="DietOptions">
					@{
						List<PinewoodGrow.ViewModels.CheckOptionVM> DietOptions = ViewBag.DietOptions;
						foreach (var checkbox in DietOptions)
						{
							<div>
								<label>
									<input type="checkbox"
										   name="selectedDietOptions"
										   value="@checkbox.ID"
										   @(Html.Raw(checkbox.Assigned ? "checked=\"checked\"" : "")) />
									<span>
										@checkbox.DisplayText
									</span>
								</label>
							</div>
						}
					}

				</div>
			</div>
        </div>
        <div class="form-group">
            <h2>Illnesses</h2>
			<div class="col-md-offset-1">
				@if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
				{
					<button class="btn btn-outline-secondary btn-sm" id="nowAddDietary"
							data-toggle="modal" data-target="#addIllnessModal"
							type="button">
						<strong>Add Illness</strong>
					</button>
				}
				<div class="checkContainer" id="IllnessOptions">
					@{
						List<PinewoodGrow.ViewModels.CheckOptionVM> illnessCheckboxes = ViewBag.IllnessOptions;
						foreach (var checkbox in illnessCheckboxes)
						{
							<div>
								<label>
									<input type="checkbox"
										   name="selectedIllnessOptions"
										   value="@checkbox.ID"
										   @(Html.Raw(checkbox.Assigned ? "checked=\"checked\"" : "")) />
									<span>
										@checkbox.DisplayText
									</span>
								</label>
							</div>
						}
					}

				</div>
			</div>
        </div>
            <div class="form-group" id="ListMemberSituations">
                <label class="control-label"><strong>Income Sources</strong> &nbsp; &nbsp;</label><button class="btn btn-outline-success modal-link" tag="" name="CreateForm" data-toggle="modal" data-target="#theMemberSituationModal" title="Add Situation" type="button">&#x271A;</button>
                <div class="col-md-offset-1" id="MemberSituationList">
                    <table>
                        @{
                            foreach (var item in Model.MemberSituations.OrderBy(s => s.Situation.Name))
                            {
                                @:<tr><td>
                                @item.Summary
                                @:</td><td>
                                @:&nbsp; &nbsp;
                                <button class="btn btn-sm modal-link" tag="@item.ID" name="EditForm" data-toggle="modal" data-target="#theMemberSituationModal" title="Edit @item.Summary" type="button">&#x270D;</button>
                                <button class="btn btn-sm modal-link" tag="@item.ID" name="DeleteForm" data-toggle="modal" data-target="#theMemberSituationModal" title="Delete @item.Summary" type="button">&#x274C;</button>
                                @:</td></tr>
                            }
                        }
                    </table>
                </div>
            </div>
        </div>
        <div class="row" style="margin: 0 auto; padding: 10px;">
            <div class="form-group" style="padding-right: 20px">
                <a data-dismiss="modal" class="btn btn-primary">Back</a>
            </div>
            <div class="form-group">
                <input type="submit" id="submitTempMemberForm" value="Create" class="btn btn-info"/>
            </div>
        </div>
    </div>
     
    </form>
 

Views/TempMembers/_DeleteTempMember.cshtml
@model PinewoodGrow.Models.Temp.TempMember

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Member</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telephone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        @*<dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.FamilySize)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FamilySize)
            </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Income)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Income)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Consent)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Consent)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.VolunteerID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.VolunteerID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CompletedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CompletedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Household)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Household.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender.Name)
        </dd>
        @*<dt class = "col-sm-2">
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.Address.City)
            </dd class>*@
    </dl>

    <form asp-action="Delete"  asp-controller="TempMembers" id="TempMemberForm" >
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" id="submitTempMemberForm"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/TempMembers/_IllnessCreate.cshtml
@model PinewoodGrow.Models.Illness
<form asp-action="Create" asp-controller="Illnesses" method="post" id="createIllnessForm">
	<div class="row">
		<div class="col-md-12">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" id="submitIllnessCreate" value="Save" class="btn btn-outline-dark" />
			</div>
		</div>
	</div>
</form>

Views/TempMembers/_addIllnessModal.cshtml
<!-- Modal-->
<div class="modal fade" id="addIllnessModal" tabindex="-1" role="dialog" aria-labelledby="IllnessModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="IllnessmyModalLabel">Add New Illness</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
			<div class="modal-body">
				@{ var i = new PinewoodGrow.Models.Illness();
					<partial name="_IllnessCreate" model="i" />
				}
			</div>
		</div>
	</div>
</div>